# Generated by Django 5.0.6 on 2024-10-01 09:32

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('WRK', 'Work'), ('PRL', 'Personal'), ('STU', 'Study'), ('OTR', 'Other')], default='OTR', max_length=3)),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('IP', 'In Progress'), ('COM', 'Completed'), ('OVD', 'Overdue')], default='PND', max_length=3)),
                ('priority', models.CharField(choices=[('lw', 'Low'), ('md', 'Medium'), ('hg', 'High')], default='md', max_length=2)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(validators=[core.models.validate_due_date])),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
